version: 1
policies:
  - id: cf-autotick-bot-test-package-policy
    repo: cf-autotick-bot-test-package-feedstock
    teams:
      - core
    pull_request: false
  - id: numpy-feedstock-policy
    repo: numpy-feedstock
    teams:
      - numpy-feedstock
    pull_request: false
access_control:
  - resource: cirun-openstack-gpu-large
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-gpu-xlarge
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-cpu-medium
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-cpu-large
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun
    policies:
      - numpy-feedstock-policy
