version: 1
policies:
  - id: cf-autotick-bot-test-package-policy
    repo: cf-autotick-bot-test-package-feedstock
    teams:
      - core
    pull_request: false
  - id: numpy-feedstock-policy
    repo: numpy-feedstock
    roles:
      - admin
      - maintain
    pull_request: false
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: pytorch-cpu-feedstock-policy
    repo: pytorch-cpu-feedstock
    roles:
      - admin
      - maintain
    pull_request: false
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
access_control:
  - resource: cirun-openstack-gpu-large
    policies:
      - cf-autotick-bot-test-package-policy
      - numpy-feedstock-policy
      - pytorch-cpu-feedstock-policy
  - resource: cirun-openstack-gpu-xlarge
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-cpu-medium
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-cpu-large
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun
    policies:
      - numpy-feedstock-policy
